#spring:
#  application:
#    name: "demo"
#server:
#  port: 8080
#management:
#  endpoints:
#    web:
#      base-path: "/manage"
#logging:
#  level:
#    root: "INFO"
spring:
  application:
    name: "demo"
  r2dbc:
    initialize-schema: "embedded"
    url: "r2dbc:h2:mem:///db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;"
    username: sa
    password:
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: "/manage"
logging:
  level:
    root: "DEBUG"
    org.springframework.data.r2dbc: INFO
    io.r2dbc.spi: INFO
domain:
  name: http://localhost:3000