spring:
  application:
    name: "demo"
  r2dbc:
    url: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: "/manage"
logging:
  level:
    root: "DEBUG"