#spring:
#  application:
#    name: "demo"
#server:
#  port: 8080
#management:
#  endpoints:
#    web:
#      base-path: "/manage"
#logging:
#  level:
#    root: "INFO"
spring:
  application:
    name: "demo"
  r2dbc:
    initialize-schema: "embedded"
    url: "r2dbc:h2:mem:///db;DB_CLOSE_ON_EXIT=TRUE;"
    username: sa
    password:
server:
  port: 8080
  ssl:
    key-store: "springboot.p12"
    key-store-password: "admin"
    key-store-type: PKCS12
    key-alias: springboot
management:
  endpoints:
    web:
      base-path: "/manage"
      exposure:
        include: health,info
  metrics:
    export:
      simple:
        enabled: true
        step: 1m
logging:
  level:
    root: "DEBUG"
    org.springframework.data.r2dbc: INFO
    io.r2dbc.spi: INFO
domain:
  name: http://localhost:3000
mfa:
  secret: ${MFA_SECRET_KEY:Undefined} # Make sure to encode to Base64
app:
  security:
    filters:
      cookies:
        enabled: true
        permitted-paths:
          - "/api/v1/auth/**"