spring:
  application:
    name: "demo"
  r2dbc:
    initialize-schema: "embedded"
    url: "r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=TRUE;"
    username: sa
    password:
server:
  port: 8080
  ssl:
    key-store: "springboot.p12"
    key-store-password: "admin"
    key-store-type: PKCS12
    key-alias: springboot
management:
  endpoints:
    web:
      base-path: "/manage"
logging:
  level:
    root: "INFO"
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.spi: DEBUG
domain:
  name: http://localhost:3000
mfa:
  secret: ${MFA_SECRET_KEY:Undefined} # Make sure to encode to Base64
app:
  security:
    filters:
      cookies:
        enabled: true
        permitted-paths:
          - "/api/v1/auth/**"